"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const persona_1 = require("./persona");
const direccion_1 = require("./direccion");
const telefono_1 = require("./telefono");
const mail_1 = require("./mail");
const ResidenciaAna = new direccion_1.Direccion('Avda. del Mediterráneo', 7, '1', 'A', 28007, 'Retiro', 'Madrid');
const TelefonoAna = new telefono_1.Telefono('Móvil', 600427450);
const MailAna = new mail_1.Mail('Personal', 'garsaAna@gmail.com');
const DatosAna = new persona_1.Persona('Ana', 'García Sánchez', 35, '30307519M', new Date(1998, 1, 6), 'Rosa', 'Mujer', [ResidenciaAna], [MailAna], [TelefonoAna], 'Abogada, llamar a partir de las 10:00am');
const ResidenciaJuan = new direccion_1.Direccion('Calle Paraguay', 9, '2', 'D', 36630, 'Cangas', 'Pontevedra');
const TelefonoJuan = new telefono_1.Telefono('Fijo', 986875678);
const MailJuan = new mail_1.Mail('Personal', 'juanAlonso@hotmail.com');
const DatosJuan = new persona_1.Persona('Juan', 'Alonso González', 55, '26308521V', new Date(1968, 5, 24), 'Azul', 'Hombre', [ResidenciaJuan], [MailJuan], [TelefonoJuan], 'Jefe taller BMW');
const ResidenciaSofía = new direccion_1.Direccion('Calle del Carmen', 10, '12', 'E', 30204, 'Cartagena', 'Murcia');
const TelefonoSofía = new telefono_1.Telefono('Móvil', 690141712);
const MailSofía = new mail_1.Mail('Personal', 'soysofia@gmail.com');
const DatosSofía = new persona_1.Persona('Sofía', 'Pérez LaFuente', 27, '59574412L', new Date(1996, 7, 25), 'Naranja', 'Mujer', [ResidenciaSofía], [MailSofía], [TelefonoSofía], 'Panadera');
console.log('Contactos');
console.log(DatosAna);
console.log(DatosJuan);
console.log(DatosSofía);
const Agenda = new Array(DatosAna, DatosJuan, DatosSofía);
const buscarDni = '59574412L';
const buscarPersona = Agenda.find(persona => persona.dni === buscarDni);
const nuevaDireccion = new direccion_1.Direccion('Avda. de la Marina', 2, '1', 'B', 30001, 'Torrevieja', 'Alicante');
const nuevoMail = new mail_1.Mail('Trabajo', 'pandeSofia@gmail.com');
const nuevoTelefono = new telefono_1.Telefono('Móvil Trabajo', 616502419);
buscarPersona.añadirNuevaDireccion(nuevaDireccion);
buscarPersona.añadirNuevoMail(nuevoMail);
buscarPersona.añadirNuevoTelefono(nuevoTelefono);
console.log('Contactos después de modificación');
console.log(DatosAna);
console.log(DatosJuan);
console.log(DatosSofía);
